# Generated by Django 2.2.2 on 2019-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank='True', upload_to=''),
        ),
    ]
