# Generated by Django 2.2.2 on 2019-06-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_personalinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='city',
            field=models.CharField(blank='True', max_length=55, verbose_name='City'),
        ),
    ]
