# Generated by Django 2.2.2 on 2019-06-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_personalinfo_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
