# Generated by Django 2.2.2 on 2019-06-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_personalinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('institution', models.CharField(max_length=255, verbose_name='Instution Name')),
                ('faculty', models.CharField(max_length=255, verbose_name='Faculty Name')),
                ('department', models.CharField(max_length=255, verbose_name='Department Name')),
                ('graduation', models.CharField(choices=[('Born', 'Born'), ('College', 'College'), ('High School', 'High School'), ('University', 'University'), ('Master', 'Master')], max_length=255)),
            ],
        ),
    ]
