# Generated by Django 2.2.2 on 2019-06-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_education'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Educationn',
        ),
    ]
