# Generated by Django 2.2.2 on 2019-06-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190611_0840'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Educationn',
            new_name='Education',
        ),
    ]
