# Generated by Django 2.2.2 on 2019-06-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190611_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='department',
        ),
    ]
