# Generated by Django 2.2.2 on 2019-06-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20190611_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='city',
            field=models.CharField(max_length=55, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='type',
            field=models.CharField(choices=[('Born', 'Born'), ('First School', 'First School'), ('High School', 'High School'), ('University', 'University'), ('Master', 'Master')], default='', max_length=255, verbose_name='Select Data Type'),
        ),
    ]
