# Generated by Django 2.2.2 on 2019-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190611_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(max_length=255, verbose_name='Institution Name'),
        ),
    ]
