# Generated by Django 2.2.2 on 2019-06-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20190611_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='city',
            field=models.CharField(blank='True', max_length=55, null=True, verbose_name='City Name'),
        ),
    ]
