# Generated by Django 2.2.2 on 2019-06-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20190611_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='city',
            field=models.CharField(blank='True', max_length=55, null=True, verbose_name='City Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(blank='True'),
        ),
        migrations.AlterField(
            model_name='education',
            name='department',
            field=models.CharField(blank='True', default='', max_length=255, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='faculty',
            field=models.CharField(blank='True', max_length=255, verbose_name='Faculty Name'),
        ),
        migrations.AlterField(
            model_name='education',
            name='institution',
            field=models.CharField(blank='True', max_length=255, verbose_name='Institution Name'),
        ),
    ]
