# Generated by Django 2.2.2 on 2019-06-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_education_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Sections',
        ),
    ]
