# Generated by Django 2.2.2 on 2019-06-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20190611_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='title',
            field=models.CharField(blank='True', default='', max_length=255, verbose_name='Section Title'),
        ),
    ]
