# Generated by Django 2.2.2 on 2019-06-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_sections_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Born', 'Born'), ('First School', 'First School'), ('High School', 'High School'), ('University', 'University'), ('Master', 'Master')], default='', max_length=255, verbose_name='Select Data Type')),
                ('date', models.DateField(blank='True')),
                ('image', models.ImageField(blank='False', upload_to='')),
                ('institution', models.CharField(blank='True', max_length=255, verbose_name='Institution Name')),
                ('faculty', models.CharField(blank='True', max_length=255, verbose_name='Faculty Name')),
                ('department', models.CharField(blank='True', default='', max_length=255, verbose_name='Department Name')),
                ('city', models.CharField(blank='True', max_length=55, null=True, verbose_name='City Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Sections',
        ),
    ]
