# Generated by Django 2.2.2 on 2019-06-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20190611_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank='True', default='', max_length=255, verbose_name='Section Title')),
            ],
        ),
        migrations.AddField(
            model_name='contents',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Section', verbose_name='Section Title'),
        ),
    ]
