# Generated by Django 2.2.2 on 2019-06-11 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190611_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['title'], 'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
    ]
