# Generated by Django 2.2.2 on 2019-06-11 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20190611_1157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={'ordering': ['section']},
        ),
    ]
