# Generated by Django 2.2.2 on 2019-06-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20190611_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={'ordering': ['section'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
