# Generated by Django 2.2.2 on 2019-06-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20190611_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={'ordering': ['section__title', 'type'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
    ]
