# Generated by Django 2.2.2 on 2019-06-11 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20190611_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Born', 'Born'), ('First School', 'First School'), ('High School', 'High School'), ('University', 'University'), ('Master', 'Master')], default='', max_length=255, verbose_name='Select Data Type')),
                ('date', models.DateField(blank='True')),
                ('image', models.ImageField(blank='False', upload_to='')),
                ('institution', models.CharField(blank='True', max_length=255, verbose_name='Institution Name')),
                ('faculty', models.CharField(blank='True', max_length=255, verbose_name='Faculty Name')),
                ('department', models.CharField(blank='True', default='', max_length=255, verbose_name='Department Name')),
                ('city', models.CharField(blank='True', max_length=55, null=True, verbose_name='City Name')),
                ('section', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='content_section', to='home.Section', verbose_name='Section Title')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
                'ordering': ['section__title', 'type'],
            },
        ),
        migrations.DeleteModel(
            name='Contents',
        ),
    ]
