# Generated by Django 2.2.2 on 2019-06-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20190611_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['section__title', 'title'], 'verbose_name': 'Content', 'verbose_name_plural': 'Contents'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Select Data Type'),
        ),
    ]
