# Generated by Django 2.2.2 on 2019-06-11 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20190611_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='date',
        ),
        migrations.AddField(
            model_name='content',
            name='enddate',
            field=models.CharField(blank='True', choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2017'), ('2018', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=25, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='content',
            name='startdate',
            field=models.CharField(blank='True', choices=[('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2017'), ('2018', '2019'), ('2020', '2020'), ('2021', '2021')], max_length=25, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='content',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='content_section', to='home.Section', verbose_name='Select Section'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Data Title'),
        ),
    ]
