# Generated by Django 2.2.2 on 2019-06-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20190611_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='city',
            field=models.CharField(blank='True', max_length=25, null=True, verbose_name='City Name'),
        ),
    ]
