# Generated by Django 2.2.2 on 2019-06-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20190611_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Facebook', 'facebook'), ('Twitter', 'twitter'), ('Instagram', 'instagram'), ('Whatsapp', 'whatsapp')], max_length=99, verbose_name='Select Social Media')),
                ('username', models.CharField(max_length=99, verbose_name='Username')),
                ('link', models.URLField(verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Social Account',
                'verbose_name_plural': '5 - Social Accounts',
            },
        ),
    ]
