# Generated by Django 2.2.2 on 2019-06-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20190612_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ['username', 'title'], 'verbose_name': 'Social Account', 'verbose_name_plural': '5 - Social Accounts'},
        ),
    ]
