# Generated by Django 2.2.2 on 2019-06-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190612_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publishdate',
            field=models.DateField(),
        ),
    ]
