# Generated by Django 2.2.2 on 2019-06-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190612_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Image'),
        ),
    ]
