# Generated by Django 2.2.2 on 2019-06-13 19:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenttext',
            field=ckeditor.fields.RichTextField(verbose_name='Post Content'),
        ),
    ]
